# Generated by Django 4.2.4 on 2023-12-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
