# Generated by Django 4.2.4 on 2023-12-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
